# SPDX-FileCopyrightText: mathspec Contributors
#
# SPDX-License-Identifier: MIT

name: Feature Request
description: Suggest an idea for mathspec.
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for letting us know about your idea!
  - type: textarea
    id: description
    attributes:
      label: What can be improved?
      placeholder: Tell us what you would like to see!
      value: "mathspec should be more memory efficient!"
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of mathspec are you using?
      placeholder: v0.0.1
    validations:
      required: true
